name: apiverve_cocktail
description: Cocktail is a simple tool for getting cocktail recipes. It returns the ingredients, instructions, and more of the cocktail.
version: 1.1.14
homepage: https://apiverve.com/marketplace/cocktail?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/cocktail-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
